# Generated by Django 3.2.5 on 2023-10-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='電話號碼'),
        ),
    ]
