# Generated by Django 3.2.5 on 2023-10-27 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20231026_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order'], 'verbose_name': '商品圖片', 'verbose_name_plural': '商品圖片'},
        ),
    ]
